// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: vylet_kafka.proto

package vyletkafka

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitOperation int32

const (
	CommitOperation_COMMIT_OPERATION_UNSPECIFIED CommitOperation = 0
	CommitOperation_COMMIT_OPERATION_CREATE      CommitOperation = 1
	CommitOperation_COMMIT_OPERATION_UPDATE      CommitOperation = 2
	CommitOperation_COMMIT_OPERATION_DELETE      CommitOperation = 3
)

// Enum value maps for CommitOperation.
var (
	CommitOperation_name = map[int32]string{
		0: "COMMIT_OPERATION_UNSPECIFIED",
		1: "COMMIT_OPERATION_CREATE",
		2: "COMMIT_OPERATION_UPDATE",
		3: "COMMIT_OPERATION_DELETE",
	}
	CommitOperation_value = map[string]int32{
		"COMMIT_OPERATION_UNSPECIFIED": 0,
		"COMMIT_OPERATION_CREATE":      1,
		"COMMIT_OPERATION_UPDATE":      2,
		"COMMIT_OPERATION_DELETE":      3,
	}
)

func (x CommitOperation) Enum() *CommitOperation {
	p := new(CommitOperation)
	*p = x
	return p
}

func (x CommitOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommitOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_vylet_kafka_proto_enumTypes[0].Descriptor()
}

func (CommitOperation) Type() protoreflect.EnumType {
	return &file_vylet_kafka_proto_enumTypes[0]
}

func (x CommitOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommitOperation.Descriptor instead.
func (CommitOperation) EnumDescriptor() ([]byte, []int) {
	return file_vylet_kafka_proto_rawDescGZIP(), []int{0}
}

type FirehoseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Commit        *Commit                `protobuf:"bytes,3,opt,name=commit,proto3,oneof" json:"commit,omitempty"`
	Account       []byte                 `protobuf:"bytes,4,opt,name=account,proto3,oneof" json:"account,omitempty"`
	Identity      []byte                 `protobuf:"bytes,5,opt,name=identity,proto3,oneof" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirehoseEvent) Reset() {
	*x = FirehoseEvent{}
	mi := &file_vylet_kafka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirehoseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirehoseEvent) ProtoMessage() {}

func (x *FirehoseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vylet_kafka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirehoseEvent.ProtoReflect.Descriptor instead.
func (*FirehoseEvent) Descriptor() ([]byte, []int) {
	return file_vylet_kafka_proto_rawDescGZIP(), []int{0}
}

func (x *FirehoseEvent) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *FirehoseEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FirehoseEvent) GetCommit() *Commit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *FirehoseEvent) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *FirehoseEvent) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rev           string                 `protobuf:"bytes,1,opt,name=rev,proto3" json:"rev,omitempty"`
	Operation     CommitOperation        `protobuf:"varint,2,opt,name=operation,proto3,enum=vyletkafka.CommitOperation" json:"operation,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Rkey          string                 `protobuf:"bytes,4,opt,name=rkey,proto3" json:"rkey,omitempty"`
	Record        []byte                 `protobuf:"bytes,5,opt,name=record,proto3" json:"record,omitempty"` // json.RawMessage as opaque bytes
	Cid           string                 `protobuf:"bytes,6,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_vylet_kafka_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_vylet_kafka_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_vylet_kafka_proto_rawDescGZIP(), []int{1}
}

func (x *Commit) GetRev() string {
	if x != nil {
		return x.Rev
	}
	return ""
}

func (x *Commit) GetOperation() CommitOperation {
	if x != nil {
		return x.Operation
	}
	return CommitOperation_COMMIT_OPERATION_UNSPECIFIED
}

func (x *Commit) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Commit) GetRkey() string {
	if x != nil {
		return x.Rkey
	}
	return ""
}

func (x *Commit) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *Commit) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type SequenceCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SavedOnExit   bool                   `protobuf:"varint,2,opt,name=saved_on_exit,json=savedOnExit,proto3" json:"saved_on_exit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceCursor) Reset() {
	*x = SequenceCursor{}
	mi := &file_vylet_kafka_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceCursor) ProtoMessage() {}

func (x *SequenceCursor) ProtoReflect() protoreflect.Message {
	mi := &file_vylet_kafka_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceCursor.ProtoReflect.Descriptor instead.
func (*SequenceCursor) Descriptor() ([]byte, []int) {
	return file_vylet_kafka_proto_rawDescGZIP(), []int{2}
}

func (x *SequenceCursor) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SequenceCursor) GetSavedOnExit() bool {
	if x != nil {
		return x.SavedOnExit
	}
	return false
}

var File_vylet_kafka_proto protoreflect.FileDescriptor

const file_vylet_kafka_proto_rawDesc = "" +
	"\n" +
	"\x11vylet_kafka.proto\x12\n" +
	"vyletkafka\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x02\n" +
	"\rFirehoseEvent\x12\x18\n" +
	"\x03did\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03did\x12@\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\ttimestamp\x12/\n" +
	"\x06commit\x18\x03 \x01(\v2\x12.vyletkafka.CommitH\x00R\x06commit\x88\x01\x01\x12\x1d\n" +
	"\aaccount\x18\x04 \x01(\fH\x01R\aaccount\x88\x01\x01\x12\x1f\n" +
	"\bidentity\x18\x05 \x01(\fH\x02R\bidentity\x88\x01\x01B\t\n" +
	"\a_commitB\n" +
	"\n" +
	"\b_accountB\v\n" +
	"\t_identity\"\xb3\x01\n" +
	"\x06Commit\x12\x10\n" +
	"\x03rev\x18\x01 \x01(\tR\x03rev\x129\n" +
	"\toperation\x18\x02 \x01(\x0e2\x1b.vyletkafka.CommitOperationR\toperation\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04rkey\x18\x04 \x01(\tR\x04rkey\x12\x16\n" +
	"\x06record\x18\x05 \x01(\fR\x06record\x12\x10\n" +
	"\x03cid\x18\x06 \x01(\tR\x03cid\"P\n" +
	"\x0eSequenceCursor\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12\"\n" +
	"\rsaved_on_exit\x18\x02 \x01(\bR\vsavedOnExit*\x8a\x01\n" +
	"\x0fCommitOperation\x12 \n" +
	"\x1cCOMMIT_OPERATION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17COMMIT_OPERATION_CREATE\x10\x01\x12\x1b\n" +
	"\x17COMMIT_OPERATION_UPDATE\x10\x02\x12\x1b\n" +
	"\x17COMMIT_OPERATION_DELETE\x10\x03Bx\n" +
	"\x0ecom.vyletkafkaB\x0fVyletKafkaProtoP\x01Z\r./;vyletkafka\xa2\x02\x03VXX\xaa\x02\n" +
	"Vyletkafka\xca\x02\n" +
	"Vyletkafka\xe2\x02\x16Vyletkafka\\GPBMetadata\xea\x02\n" +
	"Vyletkafkab\x06proto3"

var (
	file_vylet_kafka_proto_rawDescOnce sync.Once
	file_vylet_kafka_proto_rawDescData []byte
)

func file_vylet_kafka_proto_rawDescGZIP() []byte {
	file_vylet_kafka_proto_rawDescOnce.Do(func() {
		file_vylet_kafka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vylet_kafka_proto_rawDesc), len(file_vylet_kafka_proto_rawDesc)))
	})
	return file_vylet_kafka_proto_rawDescData
}

var file_vylet_kafka_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vylet_kafka_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vylet_kafka_proto_goTypes = []any{
	(CommitOperation)(0),          // 0: vyletkafka.CommitOperation
	(*FirehoseEvent)(nil),         // 1: vyletkafka.FirehoseEvent
	(*Commit)(nil),                // 2: vyletkafka.Commit
	(*SequenceCursor)(nil),        // 3: vyletkafka.SequenceCursor
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_vylet_kafka_proto_depIdxs = []int32{
	4, // 0: vyletkafka.FirehoseEvent.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: vyletkafka.FirehoseEvent.commit:type_name -> vyletkafka.Commit
	0, // 2: vyletkafka.Commit.operation:type_name -> vyletkafka.CommitOperation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vylet_kafka_proto_init() }
func file_vylet_kafka_proto_init() {
	if File_vylet_kafka_proto != nil {
		return
	}
	file_vylet_kafka_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vylet_kafka_proto_rawDesc), len(file_vylet_kafka_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vylet_kafka_proto_goTypes,
		DependencyIndexes: file_vylet_kafka_proto_depIdxs,
		EnumInfos:         file_vylet_kafka_proto_enumTypes,
		MessageInfos:      file_vylet_kafka_proto_msgTypes,
	}.Build()
	File_vylet_kafka_proto = out.File
	file_vylet_kafka_proto_goTypes = nil
	file_vylet_kafka_proto_depIdxs = nil
}
