// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.vylet.actor.defs

package vylet

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
)

// ActorDefs_ProfileView is a "profileView" in the app.vylet.actor.defs schema.
type ActorDefs_ProfileView struct {
	Avatar      *string                       `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	CreatedAt   *string                       `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Description *string                       `json:"description,omitempty" cborgen:"description,omitempty"`
	Did         string                        `json:"did" cborgen:"did"`
	DisplayName *string                       `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Handle      string                        `json:"handle" cborgen:"handle"`
	IndexedAt   *string                       `json:"indexedAt,omitempty" cborgen:"indexedAt,omitempty"`
	Labels      []*comatproto.LabelDefs_Label `json:"labels,omitempty" cborgen:"labels,omitempty"`
	Pronouns    *string                       `json:"pronouns,omitempty" cborgen:"pronouns,omitempty"`
	Viewer      *ActorDefs_ViewerState        `json:"viewer,omitempty" cborgen:"viewer,omitempty"`
}

// ActorDefs_ProfileViewBasic is a "profileViewBasic" in the app.vylet.actor.defs schema.
type ActorDefs_ProfileViewBasic struct {
	Avatar      *string                       `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	CreatedAt   *string                       `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Did         string                        `json:"did" cborgen:"did"`
	DisplayName *string                       `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Handle      string                        `json:"handle" cborgen:"handle"`
	Labels      []*comatproto.LabelDefs_Label `json:"labels,omitempty" cborgen:"labels,omitempty"`
	Pronouns    *string                       `json:"pronouns,omitempty" cborgen:"pronouns,omitempty"`
	Viewer      *ActorDefs_ViewerState        `json:"viewer,omitempty" cborgen:"viewer,omitempty"`
}

// ActorDefs_ViewerState is a "viewerState" in the app.vylet.actor.defs schema.
//
// Metadata about the requesting account's relationship with the subject account. Only has meaningful content for authed requests.
type ActorDefs_ViewerState struct {
	BlockedBy  *bool   `json:"blockedBy,omitempty" cborgen:"blockedBy,omitempty"`
	Blocking   *string `json:"blocking,omitempty" cborgen:"blocking,omitempty"`
	FollowedBy *string `json:"followedBy,omitempty" cborgen:"followedBy,omitempty"`
	Following  *string `json:"following,omitempty" cborgen:"following,omitempty"`
	Muted      *bool   `json:"muted,omitempty" cborgen:"muted,omitempty"`
}
