// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.vylet.actor.profile

package vylet

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("app.vylet.actor.profile", &ActorProfile{})
}

type ActorProfile struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.vylet.actor.profile"`
	// avatar: Small image to be displayed next to posts from account.
	Avatar    *lexutil.LexBlob `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	CreatedAt *string          `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	// description: Free-form profile description text.
	Description *string `json:"description,omitempty" cborgen:"description,omitempty"`
	DisplayName *string `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	// pronouns: Free-form pronouns text.
	Pronouns *string `json:"pronouns,omitempty" cborgen:"pronouns,omitempty"`
}
