// GENERATED CODE - DO NOT MODIFY
// Generated by vylet-app/handlergen

package handlers

import (
	"net/http"

	"github.com/labstack/echo/v4"
)

type FeedGetActorPostsInput struct {
	Actor string `query:"actor"`
	Cursor *string `query:"cursor"`
	Limit *int64 `query:"limit"`
}

func (h *Handlers) HandleFeedGetActorPosts(e echo.Context) error {
	var input FeedGetActorPostsInput
	if err := e.Bind(&input); err != nil {
		logger := h.server.Logger().With("handler", "HandleFeedGetActorPosts")
		logger.Error("error binding request", "err", err)
		return echo.NewHTTPError(http.StatusInternalServerError, "Internal Server Error")
	}

	output, err := h.server.HandleFeedGetActorPosts(e, &input)
	if err != nil {
		return err
	}

	return e.JSON(http.StatusOK, &output)
}
