// GENERATED CODE - DO NOT MODIFY
// Generated by vylet-app/handlergen

package handlers

import (
	"net/http"

	"github.com/labstack/echo/v4"
)

type FeedGetSubjectLikesInput struct {
	Uri string `query:"uri"`
	Limit *int64 `query:"limit"`
	Cursor *string `query:"cursor"`
}

func (h *Handlers) HandleFeedGetSubjectLikes(e echo.Context) error {
	var input FeedGetSubjectLikesInput
	if err := e.Bind(&input); err != nil {
		logger := h.server.Logger().With("handler", "HandleFeedGetSubjectLikes")
		logger.Error("error binding request", "err", err)
		return echo.NewHTTPError(http.StatusInternalServerError, "Internal Server Error")
	}

	output, err := h.server.HandleFeedGetSubjectLikes(e, &input)
	if err != nil {
		return err
	}

	return e.JSON(http.StatusOK, &output)
}
