// GENERATED CODE - DO NOT MODIFY
// Generated by vylet-app/handlergen

package handlers

import (
	"net/http"

	"github.com/labstack/echo/v4"
)

type FeedGetPostsInput struct {
	Uris []string `query:"uris"`
}

func (h *Handlers) HandleFeedGetPosts(e echo.Context) error {
	var input FeedGetPostsInput
	if err := e.Bind(&input); err != nil {
		logger := h.server.Logger().With("handler", "HandleFeedGetPosts")
		logger.Error("error binding request", "err", err)
		return echo.NewHTTPError(http.StatusInternalServerError, "Internal Server Error")
	}

	output, err := h.server.HandleFeedGetPosts(e, &input)
	if err != nil {
		return err
	}

	return e.JSON(http.StatusOK, &output)
}
