// GENERATED CODE - DO NOT MODIFY
// Generated by vylet-app/handlergen

package handlers

import (
	"log/slog"
	"net/http"

	"github.com/labstack/echo/v4"
	vylet "github.com/vylet-app/go/generated/vylet"
)

type Server interface {
	Logger() *slog.Logger

	HandleActorGetProfile(e echo.Context, input *ActorGetProfileInput) (*vylet.ActorDefs_ProfileView, *echo.HTTPError)
	ActorGetProfileRequiresAuth() bool
	HandleActorGetProfiles(e echo.Context, input *ActorGetProfilesInput) (*vylet.ActorGetProfiles_Output, *echo.HTTPError)
	ActorGetProfilesRequiresAuth() bool
	HandleFeedGetActorPosts(e echo.Context, input *FeedGetActorPostsInput) (*vylet.FeedGetActorPosts_Output, *echo.HTTPError)
	FeedGetActorPostsRequiresAuth() bool
	HandleFeedGetPosts(e echo.Context, input *FeedGetPostsInput) (*vylet.FeedGetPosts_Output, *echo.HTTPError)
	FeedGetPostsRequiresAuth() bool
	HandleFeedGetSubjectLikes(e echo.Context, input *FeedGetSubjectLikesInput) (*vylet.FeedGetSubjectLikes_Output, *echo.HTTPError)
	FeedGetSubjectLikesRequiresAuth() bool
}

type Handlers struct {
	server Server
}

func RegisterHandlers(e *echo.Echo, s Server) {
	h := Handlers{
		server: s,
	}

	e.GET("/xrpc/app.vylet.actor.getProfile", h.HandleActorGetProfile, CreateAuthRequiredMiddleware(s.ActorGetProfileRequiresAuth()))
	e.GET("/xrpc/app.vylet.actor.getProfiles", h.HandleActorGetProfiles, CreateAuthRequiredMiddleware(s.ActorGetProfilesRequiresAuth()))
	e.GET("/xrpc/app.vylet.feed.getActorPosts", h.HandleFeedGetActorPosts, CreateAuthRequiredMiddleware(s.FeedGetActorPostsRequiresAuth()))
	e.GET("/xrpc/app.vylet.feed.getPosts", h.HandleFeedGetPosts, CreateAuthRequiredMiddleware(s.FeedGetPostsRequiresAuth()))
	e.GET("/xrpc/app.vylet.feed.getSubjectLikes", h.HandleFeedGetSubjectLikes, CreateAuthRequiredMiddleware(s.FeedGetSubjectLikesRequiresAuth()))
}

func AuthRequiredMiddleware(next echo.HandlerFunc) echo.HandlerFunc {
	return func(e echo.Context) error {
		viewer, ok := e.Get("viewer").(string)
		if !ok || viewer == "" {
			return echo.NewHTTPError(http.StatusUnauthorized, "Unauthorized")
		}
		return next(e)
	}
}

func CreateAuthRequiredMiddleware(authRequired bool) echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		if authRequired {
			return AuthRequiredMiddleware(next)
		} else {
			return func(e echo.Context) error {
				return next(e)
			}
		}
	}
}
