// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blob_ref.proto

package vyletdatabase

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlobRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Did            string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Cid            string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	FirstSeenAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	ProcessedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=processed_at,json=processedAt,proto3,oneof" json:"processed_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	TakenDown      bool                   `protobuf:"varint,6,opt,name=taken_down,json=takenDown,proto3" json:"taken_down,omitempty"`
	TakedownReason *string                `protobuf:"bytes,7,opt,name=takedown_reason,json=takedownReason,proto3,oneof" json:"takedown_reason,omitempty"`
	TakenDownAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=taken_down_at,json=takenDownAt,proto3,oneof" json:"taken_down_at,omitempty"`
	Tags           []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlobRef) Reset() {
	*x = BlobRef{}
	mi := &file_blob_ref_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobRef) ProtoMessage() {}

func (x *BlobRef) ProtoReflect() protoreflect.Message {
	mi := &file_blob_ref_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobRef.ProtoReflect.Descriptor instead.
func (*BlobRef) Descriptor() ([]byte, []int) {
	return file_blob_ref_proto_rawDescGZIP(), []int{0}
}

func (x *BlobRef) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *BlobRef) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *BlobRef) GetFirstSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeenAt
	}
	return nil
}

func (x *BlobRef) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *BlobRef) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BlobRef) GetTakenDown() bool {
	if x != nil {
		return x.TakenDown
	}
	return false
}

func (x *BlobRef) GetTakedownReason() string {
	if x != nil && x.TakedownReason != nil {
		return *x.TakedownReason
	}
	return ""
}

func (x *BlobRef) GetTakenDownAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenDownAt
	}
	return nil
}

func (x *BlobRef) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetBlobRefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRefRequest) Reset() {
	*x = GetBlobRefRequest{}
	mi := &file_blob_ref_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRefRequest) ProtoMessage() {}

func (x *GetBlobRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blob_ref_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRefRequest.ProtoReflect.Descriptor instead.
func (*GetBlobRefRequest) Descriptor() ([]byte, []int) {
	return file_blob_ref_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlobRefRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetBlobRefRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type GetBlobRefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	BlobRef       *BlobRef               `protobuf:"bytes,2,opt,name=blob_ref,json=blobRef,proto3,oneof" json:"blob_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRefResponse) Reset() {
	*x = GetBlobRefResponse{}
	mi := &file_blob_ref_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRefResponse) ProtoMessage() {}

func (x *GetBlobRefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blob_ref_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRefResponse.ProtoReflect.Descriptor instead.
func (*GetBlobRefResponse) Descriptor() ([]byte, []int) {
	return file_blob_ref_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlobRefResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetBlobRefResponse) GetBlobRef() *BlobRef {
	if x != nil {
		return x.BlobRef
	}
	return nil
}

type CreateBlobRefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobRef       *BlobRef               `protobuf:"bytes,1,opt,name=blob_ref,json=blobRef,proto3" json:"blob_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlobRefRequest) Reset() {
	*x = CreateBlobRefRequest{}
	mi := &file_blob_ref_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlobRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlobRefRequest) ProtoMessage() {}

func (x *CreateBlobRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blob_ref_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlobRefRequest.ProtoReflect.Descriptor instead.
func (*CreateBlobRefRequest) Descriptor() ([]byte, []int) {
	return file_blob_ref_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBlobRefRequest) GetBlobRef() *BlobRef {
	if x != nil {
		return x.BlobRef
	}
	return nil
}

type CreateBlobRefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlobRefResponse) Reset() {
	*x = CreateBlobRefResponse{}
	mi := &file_blob_ref_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlobRefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlobRefResponse) ProtoMessage() {}

func (x *CreateBlobRefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blob_ref_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlobRefResponse.ProtoReflect.Descriptor instead.
func (*CreateBlobRefResponse) Descriptor() ([]byte, []int) {
	return file_blob_ref_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBlobRefResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type UpdateBlobRefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobRef       *BlobRef               `protobuf:"bytes,1,opt,name=blob_ref,json=blobRef,proto3" json:"blob_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlobRefRequest) Reset() {
	*x = UpdateBlobRefRequest{}
	mi := &file_blob_ref_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlobRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlobRefRequest) ProtoMessage() {}

func (x *UpdateBlobRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blob_ref_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlobRefRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlobRefRequest) Descriptor() ([]byte, []int) {
	return file_blob_ref_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBlobRefRequest) GetBlobRef() *BlobRef {
	if x != nil {
		return x.BlobRef
	}
	return nil
}

type UpdateBlobRefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlobRefResponse) Reset() {
	*x = UpdateBlobRefResponse{}
	mi := &file_blob_ref_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlobRefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlobRefResponse) ProtoMessage() {}

func (x *UpdateBlobRefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blob_ref_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlobRefResponse.ProtoReflect.Descriptor instead.
func (*UpdateBlobRefResponse) Descriptor() ([]byte, []int) {
	return file_blob_ref_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBlobRefResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_blob_ref_proto protoreflect.FileDescriptor

const file_blob_ref_proto_rawDesc = "" +
	"\n" +
	"\x0eblob_ref.proto\x12\rvyletdatabase\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x03\n" +
	"\aBlobRef\x12\x18\n" +
	"\x03did\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03did\x12\x18\n" +
	"\x03cid\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03cid\x12>\n" +
	"\rfirst_seen_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vfirstSeenAt\x12B\n" +
	"\fprocessed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vprocessedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tupdatedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"taken_down\x18\x06 \x01(\bR\ttakenDown\x12,\n" +
	"\x0ftakedown_reason\x18\a \x01(\tH\x02R\x0etakedownReason\x88\x01\x01\x12C\n" +
	"\rtaken_down_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x03R\vtakenDownAt\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tagsB\x0f\n" +
	"\r_processed_atB\r\n" +
	"\v_updated_atB\x12\n" +
	"\x10_takedown_reasonB\x10\n" +
	"\x0e_taken_down_at\"G\n" +
	"\x11GetBlobRefRequest\x12\x18\n" +
	"\x03did\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03did\x12\x18\n" +
	"\x03cid\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03cid\"~\n" +
	"\x12GetBlobRefResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x126\n" +
	"\bblob_ref\x18\x02 \x01(\v2\x16.vyletdatabase.BlobRefH\x01R\ablobRef\x88\x01\x01B\b\n" +
	"\x06_errorB\v\n" +
	"\t_blob_ref\"I\n" +
	"\x14CreateBlobRefRequest\x121\n" +
	"\bblob_ref\x18\x01 \x01(\v2\x16.vyletdatabase.BlobRefR\ablobRef\"<\n" +
	"\x15CreateBlobRefResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"I\n" +
	"\x14UpdateBlobRefRequest\x121\n" +
	"\bblob_ref\x18\x01 \x01(\v2\x16.vyletdatabase.BlobRefR\ablobRef\"<\n" +
	"\x15UpdateBlobRefResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\x9b\x02\n" +
	"\x0eBlobRefService\x12Q\n" +
	"\n" +
	"GetBlobRef\x12 .vyletdatabase.GetBlobRefRequest\x1a!.vyletdatabase.GetBlobRefResponse\x12Z\n" +
	"\rCreateBlobRef\x12#.vyletdatabase.CreateBlobRefRequest\x1a$.vyletdatabase.CreateBlobRefResponse\x12Z\n" +
	"\rUpdateBlobRef\x12#.vyletdatabase.UpdateBlobRefRequest\x1a$.vyletdatabase.UpdateBlobRefResponseB\x87\x01\n" +
	"\x11com.vyletdatabaseB\fBlobRefProtoP\x01Z\x10./;vyletdatabase\xa2\x02\x03VXX\xaa\x02\rVyletdatabase\xca\x02\rVyletdatabase\xe2\x02\x19Vyletdatabase\\GPBMetadata\xea\x02\rVyletdatabaseb\x06proto3"

var (
	file_blob_ref_proto_rawDescOnce sync.Once
	file_blob_ref_proto_rawDescData []byte
)

func file_blob_ref_proto_rawDescGZIP() []byte {
	file_blob_ref_proto_rawDescOnce.Do(func() {
		file_blob_ref_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blob_ref_proto_rawDesc), len(file_blob_ref_proto_rawDesc)))
	})
	return file_blob_ref_proto_rawDescData
}

var file_blob_ref_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_blob_ref_proto_goTypes = []any{
	(*BlobRef)(nil),               // 0: vyletdatabase.BlobRef
	(*GetBlobRefRequest)(nil),     // 1: vyletdatabase.GetBlobRefRequest
	(*GetBlobRefResponse)(nil),    // 2: vyletdatabase.GetBlobRefResponse
	(*CreateBlobRefRequest)(nil),  // 3: vyletdatabase.CreateBlobRefRequest
	(*CreateBlobRefResponse)(nil), // 4: vyletdatabase.CreateBlobRefResponse
	(*UpdateBlobRefRequest)(nil),  // 5: vyletdatabase.UpdateBlobRefRequest
	(*UpdateBlobRefResponse)(nil), // 6: vyletdatabase.UpdateBlobRefResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_blob_ref_proto_depIdxs = []int32{
	7,  // 0: vyletdatabase.BlobRef.first_seen_at:type_name -> google.protobuf.Timestamp
	7,  // 1: vyletdatabase.BlobRef.processed_at:type_name -> google.protobuf.Timestamp
	7,  // 2: vyletdatabase.BlobRef.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 3: vyletdatabase.BlobRef.taken_down_at:type_name -> google.protobuf.Timestamp
	0,  // 4: vyletdatabase.GetBlobRefResponse.blob_ref:type_name -> vyletdatabase.BlobRef
	0,  // 5: vyletdatabase.CreateBlobRefRequest.blob_ref:type_name -> vyletdatabase.BlobRef
	0,  // 6: vyletdatabase.UpdateBlobRefRequest.blob_ref:type_name -> vyletdatabase.BlobRef
	1,  // 7: vyletdatabase.BlobRefService.GetBlobRef:input_type -> vyletdatabase.GetBlobRefRequest
	3,  // 8: vyletdatabase.BlobRefService.CreateBlobRef:input_type -> vyletdatabase.CreateBlobRefRequest
	5,  // 9: vyletdatabase.BlobRefService.UpdateBlobRef:input_type -> vyletdatabase.UpdateBlobRefRequest
	2,  // 10: vyletdatabase.BlobRefService.GetBlobRef:output_type -> vyletdatabase.GetBlobRefResponse
	4,  // 11: vyletdatabase.BlobRefService.CreateBlobRef:output_type -> vyletdatabase.CreateBlobRefResponse
	6,  // 12: vyletdatabase.BlobRefService.UpdateBlobRef:output_type -> vyletdatabase.UpdateBlobRefResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_blob_ref_proto_init() }
func file_blob_ref_proto_init() {
	if File_blob_ref_proto != nil {
		return
	}
	file_blob_ref_proto_msgTypes[0].OneofWrappers = []any{}
	file_blob_ref_proto_msgTypes[2].OneofWrappers = []any{}
	file_blob_ref_proto_msgTypes[4].OneofWrappers = []any{}
	file_blob_ref_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blob_ref_proto_rawDesc), len(file_blob_ref_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blob_ref_proto_goTypes,
		DependencyIndexes: file_blob_ref_proto_depIdxs,
		MessageInfos:      file_blob_ref_proto_msgTypes,
	}.Build()
	File_blob_ref_proto = out.File
	file_blob_ref_proto_goTypes = nil
	file_blob_ref_proto_depIdxs = nil
}
