// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: blob_ref.proto

package vyletdatabase

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlobRefService_GetBlobRef_FullMethodName    = "/vyletdatabase.BlobRefService/GetBlobRef"
	BlobRefService_CreateBlobRef_FullMethodName = "/vyletdatabase.BlobRefService/CreateBlobRef"
	BlobRefService_UpdateBlobRef_FullMethodName = "/vyletdatabase.BlobRefService/UpdateBlobRef"
)

// BlobRefServiceClient is the client API for BlobRefService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlobRefServiceClient interface {
	GetBlobRef(ctx context.Context, in *GetBlobRefRequest, opts ...grpc.CallOption) (*GetBlobRefResponse, error)
	CreateBlobRef(ctx context.Context, in *CreateBlobRefRequest, opts ...grpc.CallOption) (*CreateBlobRefResponse, error)
	UpdateBlobRef(ctx context.Context, in *UpdateBlobRefRequest, opts ...grpc.CallOption) (*UpdateBlobRefResponse, error)
}

type blobRefServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobRefServiceClient(cc grpc.ClientConnInterface) BlobRefServiceClient {
	return &blobRefServiceClient{cc}
}

func (c *blobRefServiceClient) GetBlobRef(ctx context.Context, in *GetBlobRefRequest, opts ...grpc.CallOption) (*GetBlobRefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlobRefResponse)
	err := c.cc.Invoke(ctx, BlobRefService_GetBlobRef_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobRefServiceClient) CreateBlobRef(ctx context.Context, in *CreateBlobRefRequest, opts ...grpc.CallOption) (*CreateBlobRefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBlobRefResponse)
	err := c.cc.Invoke(ctx, BlobRefService_CreateBlobRef_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobRefServiceClient) UpdateBlobRef(ctx context.Context, in *UpdateBlobRefRequest, opts ...grpc.CallOption) (*UpdateBlobRefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBlobRefResponse)
	err := c.cc.Invoke(ctx, BlobRefService_UpdateBlobRef_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobRefServiceServer is the server API for BlobRefService service.
// All implementations must embed UnimplementedBlobRefServiceServer
// for forward compatibility.
type BlobRefServiceServer interface {
	GetBlobRef(context.Context, *GetBlobRefRequest) (*GetBlobRefResponse, error)
	CreateBlobRef(context.Context, *CreateBlobRefRequest) (*CreateBlobRefResponse, error)
	UpdateBlobRef(context.Context, *UpdateBlobRefRequest) (*UpdateBlobRefResponse, error)
	mustEmbedUnimplementedBlobRefServiceServer()
}

// UnimplementedBlobRefServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlobRefServiceServer struct{}

func (UnimplementedBlobRefServiceServer) GetBlobRef(context.Context, *GetBlobRefRequest) (*GetBlobRefResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlobRef not implemented")
}
func (UnimplementedBlobRefServiceServer) CreateBlobRef(context.Context, *CreateBlobRefRequest) (*CreateBlobRefResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBlobRef not implemented")
}
func (UnimplementedBlobRefServiceServer) UpdateBlobRef(context.Context, *UpdateBlobRefRequest) (*UpdateBlobRefResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBlobRef not implemented")
}
func (UnimplementedBlobRefServiceServer) mustEmbedUnimplementedBlobRefServiceServer() {}
func (UnimplementedBlobRefServiceServer) testEmbeddedByValue()                        {}

// UnsafeBlobRefServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobRefServiceServer will
// result in compilation errors.
type UnsafeBlobRefServiceServer interface {
	mustEmbedUnimplementedBlobRefServiceServer()
}

func RegisterBlobRefServiceServer(s grpc.ServiceRegistrar, srv BlobRefServiceServer) {
	// If the following call panics, it indicates UnimplementedBlobRefServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlobRefService_ServiceDesc, srv)
}

func _BlobRefService_GetBlobRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobRefServiceServer).GetBlobRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobRefService_GetBlobRef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobRefServiceServer).GetBlobRef(ctx, req.(*GetBlobRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobRefService_CreateBlobRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlobRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobRefServiceServer).CreateBlobRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobRefService_CreateBlobRef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobRefServiceServer).CreateBlobRef(ctx, req.(*CreateBlobRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobRefService_UpdateBlobRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlobRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobRefServiceServer).UpdateBlobRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobRefService_UpdateBlobRef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobRefServiceServer).UpdateBlobRef(ctx, req.(*UpdateBlobRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlobRefService_ServiceDesc is the grpc.ServiceDesc for BlobRefService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobRefService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vyletdatabase.BlobRefService",
	HandlerType: (*BlobRefServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlobRef",
			Handler:    _BlobRefService_GetBlobRef_Handler,
		},
		{
			MethodName: "CreateBlobRef",
			Handler:    _BlobRefService_CreateBlobRef_Handler,
		},
		{
			MethodName: "UpdateBlobRef",
			Handler:    _BlobRefService_UpdateBlobRef_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blob_ref.proto",
}
