// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: follow.proto

package vyletdatabase

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FollowService_CreateFollow_FullMethodName              = "/vyletdatabase.FollowService/CreateFollow"
	FollowService_DeleteFollow_FullMethodName              = "/vyletdatabase.FollowService/DeleteFollow"
	FollowService_GetFollowsByActor_FullMethodName         = "/vyletdatabase.FollowService/GetFollowsByActor"
	FollowService_GetFollowersByActor_FullMethodName       = "/vyletdatabase.FollowService/GetFollowersByActor"
	FollowService_GetFollowForAuthorSubject_FullMethodName = "/vyletdatabase.FollowService/GetFollowForAuthorSubject"
)

// FollowServiceClient is the client API for FollowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FollowServiceClient interface {
	CreateFollow(ctx context.Context, in *CreateFollowRequest, opts ...grpc.CallOption) (*CreateFollowResponse, error)
	DeleteFollow(ctx context.Context, in *DeleteFollowRequest, opts ...grpc.CallOption) (*DeleteFollowResponse, error)
	GetFollowsByActor(ctx context.Context, in *GetFollowsByActorRequest, opts ...grpc.CallOption) (*GetFollowsByActorResponse, error)
	GetFollowersByActor(ctx context.Context, in *GetFollowersByActorRequest, opts ...grpc.CallOption) (*GetFollowersByActorResponse, error)
	GetFollowForAuthorSubject(ctx context.Context, in *GetFollowForAuthorSubjectRequest, opts ...grpc.CallOption) (*GetFollowForAuthorSubjectResponse, error)
}

type followServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowServiceClient(cc grpc.ClientConnInterface) FollowServiceClient {
	return &followServiceClient{cc}
}

func (c *followServiceClient) CreateFollow(ctx context.Context, in *CreateFollowRequest, opts ...grpc.CallOption) (*CreateFollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFollowResponse)
	err := c.cc.Invoke(ctx, FollowService_CreateFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) DeleteFollow(ctx context.Context, in *DeleteFollowRequest, opts ...grpc.CallOption) (*DeleteFollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFollowResponse)
	err := c.cc.Invoke(ctx, FollowService_DeleteFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) GetFollowsByActor(ctx context.Context, in *GetFollowsByActorRequest, opts ...grpc.CallOption) (*GetFollowsByActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowsByActorResponse)
	err := c.cc.Invoke(ctx, FollowService_GetFollowsByActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) GetFollowersByActor(ctx context.Context, in *GetFollowersByActorRequest, opts ...grpc.CallOption) (*GetFollowersByActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowersByActorResponse)
	err := c.cc.Invoke(ctx, FollowService_GetFollowersByActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) GetFollowForAuthorSubject(ctx context.Context, in *GetFollowForAuthorSubjectRequest, opts ...grpc.CallOption) (*GetFollowForAuthorSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowForAuthorSubjectResponse)
	err := c.cc.Invoke(ctx, FollowService_GetFollowForAuthorSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowServiceServer is the server API for FollowService service.
// All implementations must embed UnimplementedFollowServiceServer
// for forward compatibility.
type FollowServiceServer interface {
	CreateFollow(context.Context, *CreateFollowRequest) (*CreateFollowResponse, error)
	DeleteFollow(context.Context, *DeleteFollowRequest) (*DeleteFollowResponse, error)
	GetFollowsByActor(context.Context, *GetFollowsByActorRequest) (*GetFollowsByActorResponse, error)
	GetFollowersByActor(context.Context, *GetFollowersByActorRequest) (*GetFollowersByActorResponse, error)
	GetFollowForAuthorSubject(context.Context, *GetFollowForAuthorSubjectRequest) (*GetFollowForAuthorSubjectResponse, error)
	mustEmbedUnimplementedFollowServiceServer()
}

// UnimplementedFollowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowServiceServer struct{}

func (UnimplementedFollowServiceServer) CreateFollow(context.Context, *CreateFollowRequest) (*CreateFollowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFollow not implemented")
}
func (UnimplementedFollowServiceServer) DeleteFollow(context.Context, *DeleteFollowRequest) (*DeleteFollowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFollow not implemented")
}
func (UnimplementedFollowServiceServer) GetFollowsByActor(context.Context, *GetFollowsByActorRequest) (*GetFollowsByActorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowsByActor not implemented")
}
func (UnimplementedFollowServiceServer) GetFollowersByActor(context.Context, *GetFollowersByActorRequest) (*GetFollowersByActorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowersByActor not implemented")
}
func (UnimplementedFollowServiceServer) GetFollowForAuthorSubject(context.Context, *GetFollowForAuthorSubjectRequest) (*GetFollowForAuthorSubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowForAuthorSubject not implemented")
}
func (UnimplementedFollowServiceServer) mustEmbedUnimplementedFollowServiceServer() {}
func (UnimplementedFollowServiceServer) testEmbeddedByValue()                       {}

// UnsafeFollowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowServiceServer will
// result in compilation errors.
type UnsafeFollowServiceServer interface {
	mustEmbedUnimplementedFollowServiceServer()
}

func RegisterFollowServiceServer(s grpc.ServiceRegistrar, srv FollowServiceServer) {
	// If the following call panics, it indicates UnimplementedFollowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowService_ServiceDesc, srv)
}

func _FollowService_CreateFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).CreateFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_CreateFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).CreateFollow(ctx, req.(*CreateFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_DeleteFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).DeleteFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_DeleteFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).DeleteFollow(ctx, req.(*DeleteFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_GetFollowsByActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowsByActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).GetFollowsByActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_GetFollowsByActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).GetFollowsByActor(ctx, req.(*GetFollowsByActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_GetFollowersByActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersByActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).GetFollowersByActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_GetFollowersByActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).GetFollowersByActor(ctx, req.(*GetFollowersByActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_GetFollowForAuthorSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowForAuthorSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).GetFollowForAuthorSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_GetFollowForAuthorSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).GetFollowForAuthorSubject(ctx, req.(*GetFollowForAuthorSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowService_ServiceDesc is the grpc.ServiceDesc for FollowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vyletdatabase.FollowService",
	HandlerType: (*FollowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFollow",
			Handler:    _FollowService_CreateFollow_Handler,
		},
		{
			MethodName: "DeleteFollow",
			Handler:    _FollowService_DeleteFollow_Handler,
		},
		{
			MethodName: "GetFollowsByActor",
			Handler:    _FollowService_GetFollowsByActor_Handler,
		},
		{
			MethodName: "GetFollowersByActor",
			Handler:    _FollowService_GetFollowersByActor_Handler,
		},
		{
			MethodName: "GetFollowForAuthorSubject",
			Handler:    _FollowService_GetFollowForAuthorSubject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "follow.proto",
}
