// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: follow.proto

package vyletdatabase

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Follow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	SubjectDid    string                 `protobuf:"bytes,3,opt,name=subject_did,json=subjectDid,proto3" json:"subject_did,omitempty"`
	AuthorDid     string                 `protobuf:"bytes,5,opt,name=author_did,json=authorDid,proto3" json:"author_did,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IndexedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow) Reset() {
	*x = Follow{}
	mi := &file_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow) ProtoMessage() {}

func (x *Follow) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow.ProtoReflect.Descriptor instead.
func (*Follow) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{0}
}

func (x *Follow) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Follow) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Follow) GetSubjectDid() string {
	if x != nil {
		return x.SubjectDid
	}
	return ""
}

func (x *Follow) GetAuthorDid() string {
	if x != nil {
		return x.AuthorDid
	}
	return ""
}

func (x *Follow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Follow) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

type CreateFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follow        *Follow                `protobuf:"bytes,1,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFollowRequest) Reset() {
	*x = CreateFollowRequest{}
	mi := &file_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFollowRequest) ProtoMessage() {}

func (x *CreateFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFollowRequest.ProtoReflect.Descriptor instead.
func (*CreateFollowRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFollowRequest) GetFollow() *Follow {
	if x != nil {
		return x.Follow
	}
	return nil
}

type CreateFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFollowResponse) Reset() {
	*x = CreateFollowResponse{}
	mi := &file_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFollowResponse) ProtoMessage() {}

func (x *CreateFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFollowResponse.ProtoReflect.Descriptor instead.
func (*CreateFollowResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFollowResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DeleteFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFollowRequest) Reset() {
	*x = DeleteFollowRequest{}
	mi := &file_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFollowRequest) ProtoMessage() {}

func (x *DeleteFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFollowRequest.ProtoReflect.Descriptor instead.
func (*DeleteFollowRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFollowRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type DeleteFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFollowResponse) Reset() {
	*x = DeleteFollowResponse{}
	mi := &file_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFollowResponse) ProtoMessage() {}

func (x *DeleteFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFollowResponse.ProtoReflect.Descriptor instead.
func (*DeleteFollowResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFollowResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetFollowsByActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowsByActorRequest) Reset() {
	*x = GetFollowsByActorRequest{}
	mi := &file_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowsByActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowsByActorRequest) ProtoMessage() {}

func (x *GetFollowsByActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowsByActorRequest.ProtoReflect.Descriptor instead.
func (*GetFollowsByActorRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{5}
}

func (x *GetFollowsByActorRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetFollowsByActorRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFollowsByActorRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type GetFollowsByActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Follows       []*Follow              `protobuf:"bytes,2,rep,name=follows,proto3" json:"follows,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,4,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowsByActorResponse) Reset() {
	*x = GetFollowsByActorResponse{}
	mi := &file_follow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowsByActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowsByActorResponse) ProtoMessage() {}

func (x *GetFollowsByActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowsByActorResponse.ProtoReflect.Descriptor instead.
func (*GetFollowsByActorResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{6}
}

func (x *GetFollowsByActorResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetFollowsByActorResponse) GetFollows() []*Follow {
	if x != nil {
		return x.Follows
	}
	return nil
}

func (x *GetFollowsByActorResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFollowsByActorResponse) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type GetFollowersByActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersByActorRequest) Reset() {
	*x = GetFollowersByActorRequest{}
	mi := &file_follow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersByActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersByActorRequest) ProtoMessage() {}

func (x *GetFollowersByActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersByActorRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersByActorRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{7}
}

func (x *GetFollowersByActorRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetFollowersByActorRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFollowersByActorRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type GetFollowersByActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Follows       []*Follow              `protobuf:"bytes,2,rep,name=follows,proto3" json:"follows,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,4,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersByActorResponse) Reset() {
	*x = GetFollowersByActorResponse{}
	mi := &file_follow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersByActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersByActorResponse) ProtoMessage() {}

func (x *GetFollowersByActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersByActorResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersByActorResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowersByActorResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetFollowersByActorResponse) GetFollows() []*Follow {
	if x != nil {
		return x.Follows
	}
	return nil
}

func (x *GetFollowersByActorResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFollowersByActorResponse) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

var File_follow_proto protoreflect.FileDescriptor

const file_follow_proto_rawDesc = "" +
	"\n" +
	"\ffollow.proto\x12\rvyletdatabase\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x01\n" +
	"\x06Follow\x12\x18\n" +
	"\x03uri\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03uri\x12\x18\n" +
	"\x03cid\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03cid\x12'\n" +
	"\vsubject_did\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"subjectDid\x12\x1d\n" +
	"\n" +
	"author_did\x18\x05 \x01(\tR\tauthorDid\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"indexed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tindexedAt\"D\n" +
	"\x13CreateFollowRequest\x12-\n" +
	"\x06follow\x18\x01 \x01(\v2\x15.vyletdatabase.FollowR\x06follow\";\n" +
	"\x14CreateFollowResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"/\n" +
	"\x13DeleteFollowRequest\x12\x18\n" +
	"\x03uri\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03uri\";\n" +
	"\x14DeleteFollowResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"r\n" +
	"\x18GetFollowsByActorRequest\x12\x18\n" +
	"\x03did\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03did\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\xaf\x01\n" +
	"\x19GetFollowsByActorResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x12/\n" +
	"\afollows\x18\x02 \x03(\v2\x15.vyletdatabase.FollowR\afollows\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x04 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_errorB\t\n" +
	"\a_cursor\"t\n" +
	"\x1aGetFollowersByActorRequest\x12\x18\n" +
	"\x03did\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03did\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\xb1\x01\n" +
	"\x1bGetFollowersByActorResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x12/\n" +
	"\afollows\x18\x02 \x03(\v2\x15.vyletdatabase.FollowR\afollows\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x04 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_errorB\t\n" +
	"\a_cursor2\x97\x03\n" +
	"\rFollowService\x12W\n" +
	"\fCreateFollow\x12\".vyletdatabase.CreateFollowRequest\x1a#.vyletdatabase.CreateFollowResponse\x12W\n" +
	"\fDeleteFollow\x12\".vyletdatabase.DeleteFollowRequest\x1a#.vyletdatabase.DeleteFollowResponse\x12f\n" +
	"\x11GetFollowsByActor\x12'.vyletdatabase.GetFollowsByActorRequest\x1a(.vyletdatabase.GetFollowsByActorResponse\x12l\n" +
	"\x13GetFollowersByActor\x12).vyletdatabase.GetFollowersByActorRequest\x1a*.vyletdatabase.GetFollowersByActorResponseB\x86\x01\n" +
	"\x11com.vyletdatabaseB\vFollowProtoP\x01Z\x10./;vyletdatabase\xa2\x02\x03VXX\xaa\x02\rVyletdatabase\xca\x02\rVyletdatabase\xe2\x02\x19Vyletdatabase\\GPBMetadata\xea\x02\rVyletdatabaseb\x06proto3"

var (
	file_follow_proto_rawDescOnce sync.Once
	file_follow_proto_rawDescData []byte
)

func file_follow_proto_rawDescGZIP() []byte {
	file_follow_proto_rawDescOnce.Do(func() {
		file_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)))
	})
	return file_follow_proto_rawDescData
}

var file_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_follow_proto_goTypes = []any{
	(*Follow)(nil),                      // 0: vyletdatabase.Follow
	(*CreateFollowRequest)(nil),         // 1: vyletdatabase.CreateFollowRequest
	(*CreateFollowResponse)(nil),        // 2: vyletdatabase.CreateFollowResponse
	(*DeleteFollowRequest)(nil),         // 3: vyletdatabase.DeleteFollowRequest
	(*DeleteFollowResponse)(nil),        // 4: vyletdatabase.DeleteFollowResponse
	(*GetFollowsByActorRequest)(nil),    // 5: vyletdatabase.GetFollowsByActorRequest
	(*GetFollowsByActorResponse)(nil),   // 6: vyletdatabase.GetFollowsByActorResponse
	(*GetFollowersByActorRequest)(nil),  // 7: vyletdatabase.GetFollowersByActorRequest
	(*GetFollowersByActorResponse)(nil), // 8: vyletdatabase.GetFollowersByActorResponse
	(*timestamppb.Timestamp)(nil),       // 9: google.protobuf.Timestamp
}
var file_follow_proto_depIdxs = []int32{
	9, // 0: vyletdatabase.Follow.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: vyletdatabase.Follow.indexed_at:type_name -> google.protobuf.Timestamp
	0, // 2: vyletdatabase.CreateFollowRequest.follow:type_name -> vyletdatabase.Follow
	0, // 3: vyletdatabase.GetFollowsByActorResponse.follows:type_name -> vyletdatabase.Follow
	0, // 4: vyletdatabase.GetFollowersByActorResponse.follows:type_name -> vyletdatabase.Follow
	1, // 5: vyletdatabase.FollowService.CreateFollow:input_type -> vyletdatabase.CreateFollowRequest
	3, // 6: vyletdatabase.FollowService.DeleteFollow:input_type -> vyletdatabase.DeleteFollowRequest
	5, // 7: vyletdatabase.FollowService.GetFollowsByActor:input_type -> vyletdatabase.GetFollowsByActorRequest
	7, // 8: vyletdatabase.FollowService.GetFollowersByActor:input_type -> vyletdatabase.GetFollowersByActorRequest
	2, // 9: vyletdatabase.FollowService.CreateFollow:output_type -> vyletdatabase.CreateFollowResponse
	4, // 10: vyletdatabase.FollowService.DeleteFollow:output_type -> vyletdatabase.DeleteFollowResponse
	6, // 11: vyletdatabase.FollowService.GetFollowsByActor:output_type -> vyletdatabase.GetFollowsByActorResponse
	8, // 12: vyletdatabase.FollowService.GetFollowersByActor:output_type -> vyletdatabase.GetFollowersByActorResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_follow_proto_init() }
func file_follow_proto_init() {
	if File_follow_proto != nil {
		return
	}
	file_follow_proto_msgTypes[2].OneofWrappers = []any{}
	file_follow_proto_msgTypes[4].OneofWrappers = []any{}
	file_follow_proto_msgTypes[5].OneofWrappers = []any{}
	file_follow_proto_msgTypes[6].OneofWrappers = []any{}
	file_follow_proto_msgTypes[7].OneofWrappers = []any{}
	file_follow_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follow_proto_goTypes,
		DependencyIndexes: file_follow_proto_depIdxs,
		MessageInfos:      file_follow_proto_msgTypes,
	}.Build()
	File_follow_proto = out.File
	file_follow_proto_goTypes = nil
	file_follow_proto_depIdxs = nil
}
