// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: like.proto

package vyletdatabase

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	SubjectUri    string                 `protobuf:"bytes,3,opt,name=subject_uri,json=subjectUri,proto3" json:"subject_uri,omitempty"`
	SubjectCid    string                 `protobuf:"bytes,4,opt,name=subject_cid,json=subjectCid,proto3" json:"subject_cid,omitempty"`
	AuthorDid     string                 `protobuf:"bytes,5,opt,name=author_did,json=authorDid,proto3" json:"author_did,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IndexedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{0}
}

func (x *Like) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Like) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Like) GetSubjectUri() string {
	if x != nil {
		return x.SubjectUri
	}
	return ""
}

func (x *Like) GetSubjectCid() string {
	if x != nil {
		return x.SubjectCid
	}
	return ""
}

func (x *Like) GetAuthorDid() string {
	if x != nil {
		return x.AuthorDid
	}
	return ""
}

func (x *Like) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Like) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

type CreateLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Like          *Like                  `protobuf:"bytes,1,opt,name=like,proto3" json:"like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLikeRequest) Reset() {
	*x = CreateLikeRequest{}
	mi := &file_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeRequest) ProtoMessage() {}

func (x *CreateLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeRequest.ProtoReflect.Descriptor instead.
func (*CreateLikeRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLikeRequest) GetLike() *Like {
	if x != nil {
		return x.Like
	}
	return nil
}

type CreateLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLikeResponse) Reset() {
	*x = CreateLikeResponse{}
	mi := &file_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeResponse) ProtoMessage() {}

func (x *CreateLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeResponse.ProtoReflect.Descriptor instead.
func (*CreateLikeResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLikeResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DeleteLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLikeRequest) Reset() {
	*x = DeleteLikeRequest{}
	mi := &file_like_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeRequest) ProtoMessage() {}

func (x *DeleteLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeRequest.ProtoReflect.Descriptor instead.
func (*DeleteLikeRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteLikeRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type DeleteLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLikeResponse) Reset() {
	*x = DeleteLikeResponse{}
	mi := &file_like_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeResponse) ProtoMessage() {}

func (x *DeleteLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeResponse.ProtoReflect.Descriptor instead.
func (*DeleteLikeResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteLikeResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetLikesBySubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectUri    string                 `protobuf:"bytes,1,opt,name=subject_uri,json=subjectUri,proto3" json:"subject_uri,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikesBySubjectRequest) Reset() {
	*x = GetLikesBySubjectRequest{}
	mi := &file_like_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikesBySubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikesBySubjectRequest) ProtoMessage() {}

func (x *GetLikesBySubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikesBySubjectRequest.ProtoReflect.Descriptor instead.
func (*GetLikesBySubjectRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{5}
}

func (x *GetLikesBySubjectRequest) GetSubjectUri() string {
	if x != nil {
		return x.SubjectUri
	}
	return ""
}

func (x *GetLikesBySubjectRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLikesBySubjectRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type GetLikesBySubjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Likes         []*Like                `protobuf:"bytes,2,rep,name=likes,proto3" json:"likes,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,4,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikesBySubjectResponse) Reset() {
	*x = GetLikesBySubjectResponse{}
	mi := &file_like_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikesBySubjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikesBySubjectResponse) ProtoMessage() {}

func (x *GetLikesBySubjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikesBySubjectResponse.ProtoReflect.Descriptor instead.
func (*GetLikesBySubjectResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{6}
}

func (x *GetLikesBySubjectResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetLikesBySubjectResponse) GetLikes() []*Like {
	if x != nil {
		return x.Likes
	}
	return nil
}

func (x *GetLikesBySubjectResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLikesBySubjectResponse) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

var File_like_proto protoreflect.FileDescriptor

const file_like_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"like.proto\x12\rvyletdatabase\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x02\n" +
	"\x04Like\x12\x18\n" +
	"\x03uri\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03uri\x12\x18\n" +
	"\x03cid\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03cid\x12'\n" +
	"\vsubject_uri\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"subjectUri\x12'\n" +
	"\vsubject_cid\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"subjectCid\x12\x1d\n" +
	"\n" +
	"author_did\x18\x05 \x01(\tR\tauthorDid\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"indexed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tindexedAt\"<\n" +
	"\x11CreateLikeRequest\x12'\n" +
	"\x04like\x18\x01 \x01(\v2\x13.vyletdatabase.LikeR\x04like\"9\n" +
	"\x12CreateLikeResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"-\n" +
	"\x11DeleteLikeRequest\x12\x18\n" +
	"\x03uri\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03uri\"9\n" +
	"\x12DeleteLikeResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x81\x01\n" +
	"\x18GetLikesBySubjectRequest\x12'\n" +
	"\vsubject_uri\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"subjectUri\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\xa9\x01\n" +
	"\x19GetLikesBySubjectResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x12)\n" +
	"\x05likes\x18\x02 \x03(\v2\x13.vyletdatabase.LikeR\x05likes\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x04 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_errorB\t\n" +
	"\a_cursor2\x9b\x02\n" +
	"\vLikeService\x12Q\n" +
	"\n" +
	"CreateLike\x12 .vyletdatabase.CreateLikeRequest\x1a!.vyletdatabase.CreateLikeResponse\x12Q\n" +
	"\n" +
	"DeleteLike\x12 .vyletdatabase.DeleteLikeRequest\x1a!.vyletdatabase.DeleteLikeResponse\x12f\n" +
	"\x11GetLikesBySubject\x12'.vyletdatabase.GetLikesBySubjectRequest\x1a(.vyletdatabase.GetLikesBySubjectResponseB\x84\x01\n" +
	"\x11com.vyletdatabaseB\tLikeProtoP\x01Z\x10./;vyletdatabase\xa2\x02\x03VXX\xaa\x02\rVyletdatabase\xca\x02\rVyletdatabase\xe2\x02\x19Vyletdatabase\\GPBMetadata\xea\x02\rVyletdatabaseb\x06proto3"

var (
	file_like_proto_rawDescOnce sync.Once
	file_like_proto_rawDescData []byte
)

func file_like_proto_rawDescGZIP() []byte {
	file_like_proto_rawDescOnce.Do(func() {
		file_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)))
	})
	return file_like_proto_rawDescData
}

var file_like_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_like_proto_goTypes = []any{
	(*Like)(nil),                      // 0: vyletdatabase.Like
	(*CreateLikeRequest)(nil),         // 1: vyletdatabase.CreateLikeRequest
	(*CreateLikeResponse)(nil),        // 2: vyletdatabase.CreateLikeResponse
	(*DeleteLikeRequest)(nil),         // 3: vyletdatabase.DeleteLikeRequest
	(*DeleteLikeResponse)(nil),        // 4: vyletdatabase.DeleteLikeResponse
	(*GetLikesBySubjectRequest)(nil),  // 5: vyletdatabase.GetLikesBySubjectRequest
	(*GetLikesBySubjectResponse)(nil), // 6: vyletdatabase.GetLikesBySubjectResponse
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
}
var file_like_proto_depIdxs = []int32{
	7, // 0: vyletdatabase.Like.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: vyletdatabase.Like.indexed_at:type_name -> google.protobuf.Timestamp
	0, // 2: vyletdatabase.CreateLikeRequest.like:type_name -> vyletdatabase.Like
	0, // 3: vyletdatabase.GetLikesBySubjectResponse.likes:type_name -> vyletdatabase.Like
	1, // 4: vyletdatabase.LikeService.CreateLike:input_type -> vyletdatabase.CreateLikeRequest
	3, // 5: vyletdatabase.LikeService.DeleteLike:input_type -> vyletdatabase.DeleteLikeRequest
	5, // 6: vyletdatabase.LikeService.GetLikesBySubject:input_type -> vyletdatabase.GetLikesBySubjectRequest
	2, // 7: vyletdatabase.LikeService.CreateLike:output_type -> vyletdatabase.CreateLikeResponse
	4, // 8: vyletdatabase.LikeService.DeleteLike:output_type -> vyletdatabase.DeleteLikeResponse
	6, // 9: vyletdatabase.LikeService.GetLikesBySubject:output_type -> vyletdatabase.GetLikesBySubjectResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_like_proto_init() }
func file_like_proto_init() {
	if File_like_proto != nil {
		return
	}
	file_like_proto_msgTypes[2].OneofWrappers = []any{}
	file_like_proto_msgTypes[4].OneofWrappers = []any{}
	file_like_proto_msgTypes[5].OneofWrappers = []any{}
	file_like_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_like_proto_goTypes,
		DependencyIndexes: file_like_proto_depIdxs,
		MessageInfos:      file_like_proto_msgTypes,
	}.Build()
	File_like_proto = out.File
	file_like_proto_goTypes = nil
	file_like_proto_depIdxs = nil
}
